Container
UMD-ARLIS/incubator-flagon-tap pull request #38
Opened 2024-02-23 19:38 UTC by rc10house

Containerizes streamline dashboard and groups it with docker-compose. Everything should work by doing a fresh container install with install.py.

2024-02-25 20:14 UTC, EandrewJones requested changes

2024-02-25 20:14 UTC, EandrewJones commented on dashboard/dashboard.py
> +    timeResp = requests.post('http://router:8888/druid/v2',
`router` is a host alias for service in docker compose. That host will not resolve outside of docker and, therefore, the dashboard won't work if you try to run it outside of docker.

Have you tried and confirmed that?

The solution here is not to hard code the url's for these API calls. Instead to dynamically select the host based on a config file and environment variable. The config file should include both the docker networking-dependent host as well as the default localhost. 

When we run the service via docker compose we can pass in an ENV var and use that to select the docker dependent route (i.e. `router`) from the config file. Otherwise, we default to `localhost`. 

This way the service will run in both environments.

2024-02-27 15:32 UTC, rc10house commented on dashboard/dashboard.py
> +    timeResp = requests.post('http://router:8888/druid/v2',
Evan, working on this right now. Can you clarify on both the config file and the environment variable? Do we need to have both of these, or can we just have a config file that the dashboard reads from and sets the domain name appropriately based on the contents of that file?

2024-02-27 17:07 UTC, rc10house commented
Updated and ready for PR.

2024-02-27 17:14 UTC, EandrewJones requested changes

2024-02-27 17:14 UTC, EandrewJones commented on dashboard/dashboard.py
> +if args.router is None : args.router = "localhost"
I'm going to be pedantic here and ask you to make this more pythonic by splitting to two lines.

```
if args.router is None:
    args.router = "localhost"
```

2024-02-27 17:26 UTC, EandrewJones approved these changes

2024-02-27 17:26 UTC, merged